<html>
    <head>
        <!-- Metadata -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Your description falls here">
        <meta name="author" content="Allen Linatoc">

        <!-- Bootstrap components -->
        <link rel="stylesheet" href="web+/bootstrap/css/bootstrap.css">

        <!-- Site components -->
        <!-- // Uncomment this if you have these files:

            <link rel="stylesheet" href="web+/site/css/default.css">
            <link rel="stylesheet" href="web+/site/css/header.css">
            <link rel="stylesheet" href="web+/site/css/footer.css">
        -->

        <title><?php echo PARAMS::Get('header_title'); ?></title>
    </head>
    <body class="row-fluid">
        <header class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <!-- Title stuff here -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Your site</a>
                </div>
                <div class="navbar-collapse collapse" style="height: 1px;">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="active"><a href="#">Home</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">My menu <span class="caret"></span></a>
                            <ul class="dropdown-menu navbar-default">
                                <li><a href="#">Add menu</a></li>
                                <li class="divider"></li>
                                <li class="dropdown-header">Menu list</li>
                                <li><a href="#">Menu1</a></li>
                                <li><a href="#">Menu2, way longer</a></li>
                            </ul>
                        </li>
                        <li><a href="#students">About</a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </header>