
    <footer class="navbar navbar-inverse navbar-fixed-bottom" id="footer">
        <!-- Put your HEADER Contents here!!! -->
        <div class="container navbar-text">
            Your footer is here!
        </div>
    </footer>


    <!-- jQuery scripts here -->
    <script type="text/javascript" src="web+/jquery/js/jquery.min.js"></script>
    
    <!-- Bootstrap components -->
    <script type="text/javascript" src="web+/bootstrap/js/bootstrap.js"></script>
    
    <!-- APHP framework scripts -->
    <script type="text/javascript" src="web+/aphp/js/flash.js"></script>
</body>
</html>